apiVersion: apps/v1
kind: Deployment
metadata:
   name: deployment-frontend
   labels:
      app: nginx
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nginx
   template:
      metadata:
         labels:
            app: nginx
      spec:
         containers:
         - name: frontend
           image: docker.io/cesarch94/flask_bootstrap_ms_demo:ui
           env:
           - name: BACKEND_API_URL
             value: "http://40.78.88.19:7777/"
           ports:
           - containerPort: 8000
