apiVersion: apps/v1
kind: Deployment
metadata:
   name: deployment-maestria-backend
   labels:
      app: nginx
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nginx
   template:
      metadata:
         labels:
            app: nginx
      spec:
         containers:
         - name: backend
           image: docker.io/cesarch94/flask_bootstrap_ms_demo:backend2
           ports:
           - containerPort: 7777
