apiVersion: apps/v1
kind: Deployment
metadata:
   name: deployment-frontend-aks
   labels:
      app: nginx
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nginx
   template:
      metadata:
         labels:
            app: nginx
      spec:
         containers:
         - name: frontend
           image: docker.io/cesarch94/flask_bootstrap_ms_demo:ui
           env:
           - name: BACKEND_API_URL
             value: "http://13.64.50.55:7777/"
           ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
   name: service-frontend-aks
   annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
   labels:
      run: service-frontend-aks
spec:
   type: LoadBalancer
   ports:
   - port: 8000
     protocol: TCP
   selector:
      app: nginx
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webserver-hpa-maestria-aks-front
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: deployment-frontend-aks
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
