apiVersion: v1
kind: Service
metadata:
   name: service-frontend
   labels:
      run: service-frontend
spec:
   type: LoadBalancer
   ports:
   - port: 8000
     protocol: TCP
   selector:
      app: nginx
